/**
 *  NEXUSe2e Business Messaging Open Source
 *  Copyright 2000-2009, Tamgroup and X-ioma GmbH
 *
 *  This is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as
 *  published by the Free Software Foundation version 2.1 of
 *  the License.
 *
 *  This software is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this software; if not, write to the Free
 *  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 *  02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.nexuse2e.pojo;

// Generated 28.11.2006 10:17:27 by Hibernate Tools 3.2.0.beta6a

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.Index;

/**
 * ConnectionPojo generated by hbm2java
 */
@Entity
@Table(name = "nx_connection")
@XmlType(name = "ConnectionType")
@XmlAccessorType(XmlAccessType.NONE)
public class ConnectionPojo implements NEXUSe2ePojo {

    /**
     * 
     */
    private static final long    serialVersionUID = -4954523807447710912L;

    // Fields    
    @Access(AccessType.PROPERTY)
    @Id
    @Column(name = "nx_connection_id")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int                  nxConnectionId;

    @ManyToOne(fetch = FetchType.EAGER)
    @Index(name = "ix_connection_1")
    @JoinColumn(name = "nx_certificate_id")
    private CertificatePojo      certificate;

    @ManyToOne(fetch = FetchType.EAGER)
    @Index(name = "ix_connection_2")
    @JoinColumn(name = "nx_trp_id")
    private TRPPojo              trp;

    @ManyToOne(fetch = FetchType.EAGER)
    @Index(name = "ix_connection_3")
    @JoinColumn(name = "nx_partner_id")
    private PartnerPojo          partner;

    @Column(name = "timeout", nullable = false)
    private int                  timeout;

    @Column(name = "message_interval", nullable = false)
    private int                  messageInterval;

    @Column(name = "security_flag", nullable = false)
    private boolean              secure;

    @Column(name = "reliable_flag", nullable = false)
    private boolean              reliable;

    @Column(name = "synchronous_flag", nullable = false)
    private boolean              synchronous;

    @Column(name = "hold", nullable = false)
    private boolean              hold;

    @Column(name = "pickup", nullable = false)
    private boolean              pickUp;

    @Column(name = "synchronous_timeout", nullable = false)
    private int                  synchronousTimeout;

    @Column(name = "retries", nullable = false)
    private int                  retries;

    @Column(name = "created_date", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date                 createdDate;

    @Column(name = "modified_date", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date                 modifiedDate;

    @Column(name = "modified_nx_user_id", nullable = false)
    private int                  modifiedNxUserId;

    @Column(name = "uri", nullable = false, length = 512)
    private String               uri;

    @Column(name = "name", nullable = false, length = 64)
    private String               name;

    @Column(name = "login_name", nullable = true, length = 64)
    private String               loginName;

    @Column(name = "password", nullable = true, length = 64)
    private String               password;

    @Column(name = "description", length = 64)
    private String               description;

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "connection")
    @Fetch(value = FetchMode.SUBSELECT)
    private Set<ParticipantPojo> participants      = new HashSet<ParticipantPojo>( 0 );
    
    @Transient
    private int                  nxTrpId;

    @Transient
    private int                  nxCertificateId;

    // Constructors

    /** default constructor */
    public ConnectionPojo() {
        createdDate = new Date();
        modifiedDate = createdDate;
    }

    /** minimal constructor */
    public ConnectionPojo( TRPPojo trp, PartnerPojo partner, int timeout, int messageInterval, boolean secure,
            boolean reliable, boolean synchronous, int synchronousTimeout, int retries, Date createdDate,
            Date modifiedDate, int modifiedNxUserId, String uri, String name ) {

        this.trp = trp;
        this.partner = partner;
        this.timeout = timeout;
        this.messageInterval = messageInterval;
        this.secure = secure;
        this.reliable = reliable;
        this.synchronous = synchronous;
        this.synchronousTimeout = synchronousTimeout;
        this.retries = retries;
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.modifiedNxUserId = modifiedNxUserId;
        this.uri = uri;
        this.name = name;
    }

    /** full constructor */
    public ConnectionPojo( CertificatePojo certificate, TRPPojo trp, PartnerPojo partner, int timeout,
            int messageInterval, boolean secure, boolean reliable, boolean synchronous, int synchronousTimeout,
            int retries, Date createdDate, Date modifiedDate, int modifiedNxUserId, String uri, String name,
            String loginName, String password, String description, Set<ParticipantPojo> partcipants ) {

        this.certificate = certificate;
        this.trp = trp;
        this.partner = partner;
        this.timeout = timeout;
        this.messageInterval = messageInterval;
        this.secure = secure;
        this.reliable = reliable;
        this.synchronous = synchronous;
        this.synchronousTimeout = synchronousTimeout;
        this.retries = retries;
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.modifiedNxUserId = modifiedNxUserId;
        this.uri = uri;
        this.name = name;
        this.loginName = loginName;
        this.password = password;
        this.description = description;
        this.participants = partcipants;
    }

    // Property accessors
    @XmlAttribute
    public int getNxConnectionId() {

        return this.nxConnectionId;
    }

    public void setNxConnectionId( int nxConnectionId ) {

        this.nxConnectionId = nxConnectionId;
    }

    public int getNxId() {
        return nxConnectionId;
    }
    
    public void setNxId( int nxId ) {
        this.nxConnectionId = nxId;
    }
    
    /**
     * Required for JAXB 
     * @return
     */
    @XmlAttribute
    public int getNxCertificateId() {

        if ( this.certificate != null ) {
            return this.certificate.getNxCertificateId();

        }
        return nxCertificateId;
    }
    
    /**
     * Required for JAXB
     * @param certificateId
     */
    public void setNxCertificateId( int certificateId ) {
        this.nxCertificateId = certificateId;
    }

    public CertificatePojo getCertificate() {

        return this.certificate;
    }

    public void setCertificate( CertificatePojo certificate ) {

        this.certificate = certificate;
    }

    /**
     * Required for JAXB 
     * @return
     */
    @XmlAttribute
    public int getNxTrpId() {

        if ( this.trp != null ) {
            return this.trp.getNxTRPId();

        }
        return nxTrpId;
    }
    
    /**
     * Required for JAXB
     */
    public void setNxTrpId( int trpId ) {
        this.nxTrpId = trpId;
    }

    public TRPPojo getTrp() {

        return this.trp;
    }

    public void setTrp( TRPPojo trp ) {

        this.trp = trp;
    }

    public PartnerPojo getPartner() {

        return this.partner;
    }

    public void setPartner( PartnerPojo partner ) {

        this.partner = partner;
    }

    @XmlAttribute
    public int getTimeout() {

        return this.timeout;
    }

    public void setTimeout( int timeout ) {

        this.timeout = timeout;
    }

    @XmlAttribute
    public int getMessageInterval() {

        return this.messageInterval;
    }

    public void setMessageInterval( int messageInterval ) {

        this.messageInterval = messageInterval;
    }

    @XmlAttribute
    public boolean isSecure() {

        return this.secure;
    }

    public void setSecure( boolean secure ) {

        this.secure = secure;
    }

    @XmlAttribute
    public boolean isReliable() {

        return this.reliable;
    }

    public void setReliable( boolean reliable ) {

        this.reliable = reliable;
    }

    @XmlAttribute
    public boolean isSynchronous() {

        return this.synchronous;
    }

    public void setSynchronous( boolean synchronous ) {

        this.synchronous = synchronous;
    }

    @XmlAttribute
    public int getSynchronousTimeout() {

        return this.synchronousTimeout;
    }

    public void setSynchronousTimeout( int synchronousTimeout ) {

        this.synchronousTimeout = synchronousTimeout;
    }

    @XmlAttribute
    public int getRetries() {

        return this.retries;
    }

    public void setRetries( int retries ) {

        this.retries = retries;
    }

    public Date getCreatedDate() {

        return this.createdDate;
    }

    public void setCreatedDate( Date createdDate ) {

        this.createdDate = createdDate;
    }

    public Date getModifiedDate() {

        return this.modifiedDate;
    }

    public void setModifiedDate( Date modifiedDate ) {

        this.modifiedDate = modifiedDate;
    }

    public int getModifiedNxUserId() {

        return this.modifiedNxUserId;
    }

    public void setModifiedNxUserId( int modifiedNxUserId ) {

        this.modifiedNxUserId = modifiedNxUserId;
    }

    @XmlAttribute
    public String getUri() {

        return this.uri;
    }

    public void setUri( String uri ) {

        this.uri = uri;
    }

    @XmlAttribute
    public String getName() {

        return this.name;
    }

    public void setName( String name ) {

        this.name = name;
    }

    @XmlAttribute
    public String getLoginName() {

        return this.loginName;
    }

    public void setLoginName( String loginName ) {

        this.loginName = loginName;
    }

    @XmlAttribute
    public String getPassword() {

        return this.password;
    }

    public void setPassword( String password ) {

        this.password = password;
    }

    @XmlAttribute
    public String getDescription() {

        return this.description;
    }

    public void setDescription( String description ) {

        this.description = description;
    }

    public Set<ParticipantPojo> getPartcipants() {

        return this.participants;
    }

    public void setPartcipants( Set<ParticipantPojo> partcipants ) {

        this.participants = partcipants;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals( Object obj ) {

        if ( !( obj instanceof ConnectionPojo ) ) {
            return false;
        }
        if ( nxConnectionId == 0 ) {
            return super.equals( obj );
        }

        return nxConnectionId == ( (ConnectionPojo) obj ).nxConnectionId;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {

        if ( nxConnectionId == 0 ) {
            return super.hashCode();
        }

        return nxConnectionId;
    }

    
    /**
     * Gets the hold flag.
     * @return <code>true</code> if this connection is held on outbound traffic,
     * <code>false</code> otherwise.
     */
    @XmlAttribute
    public boolean isHold() {
    
        return hold;
    }

    /**
     * Sets the hold flag.
     * @param hold If <code>true</code>, this outbound messages are held, otherwise not.
     */
    public void setHold( boolean hold ) {
    
        this.hold = hold;
    }

    
    /**
     * Gets the pickUp flag.
     * @return <code>true</code> if this connection is polled, <code>false</code> otherwise.
     */
    @XmlAttribute
    public boolean isPickUp() {
    
        return pickUp;
    }

    /**
     * Sets the pickUp flag.
     * @param pickUp If <code>true</code>, this connection is polled, otherwise not.
     */
    public void setPickUp( boolean pickUp ) {
    
        this.pickUp = pickUp;
    }

}
