/**
 *  NEXUSe2e Business Messaging Open Source
 *  Copyright 2000-2009, Tamgroup and X-ioma GmbH
 *
 *  This is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as
 *  published by the Free Software Foundation version 2.1 of
 *  the License.
 *
 *  This software is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this software; if not, write to the Free
 *  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 *  02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.nexuse2e.pojo;

// Generated 20.10.2006 15:50:01 by Hibernate Tools 3.2.0.beta6a

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import org.hibernate.annotations.Index;

/**
 * FollowUpActionPojo generated by hbm2java
 */
/**
 * @author mbreilmann
 *
 */
@Entity
@Table(name = "nx_follow_up_action")
@XmlType(name = "FollowUpActionType")
@XmlAccessorType(XmlAccessType.NONE)
public class FollowUpActionPojo implements NEXUSe2ePojo {

    //    public class FollowUpActionPojo implements java.io.Serializable, com.sun.xml.bind.CycleRecoverable {

    /**
     * 
     */
    private static final long serialVersionUID = -8322100357883464751L;

    // Fields

    @Id
    @Column(name = "nx_follow_up_action_id")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int               nxFollowUpActionId;

    @ManyToOne()
    @Index(name = "ix_follow_up_action_1")
    @JoinColumn(name = "nx_action_id", nullable = false)
    private ActionPojo        action;

    @ManyToOne()
    @Index(name = "ix_follow_up_action_2")
    @JoinColumn(name = "follow_up_nx_action_id", nullable = false)
    private ActionPojo        followUpAction;

    @Column(name = "created_date", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date              createdDate;

    @Column(name = "modified_date", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date              modifiedDate;

    @Column(name = "modified_nx_user_id", nullable = false)
    private int               modifiedNxUserId;

    @Transient
    private int               nxActionId;

    @Transient
    private int               refNxFollowUpActionId;
    
    // Constructors

    /** default constructor */
    public FollowUpActionPojo() {

        createdDate = new Date();
        modifiedDate = createdDate;
    }

    /** full constructor */
    public FollowUpActionPojo( ActionPojo action, ActionPojo followUpAction, Date createdDate, Date modifiedDate,
            int modifiedNxUserId ) {

        this.action = action;
        this.followUpAction = followUpAction;
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.modifiedNxUserId = modifiedNxUserId;
    }

    // Property accessors
    @XmlAttribute
    public int getNxFollowUpActionId() {

        return this.nxFollowUpActionId;
    }

    public void setNxFollowUpActionId( int nxFollowUpActionId ) {

        this.nxFollowUpActionId = nxFollowUpActionId;
    }

    public int getNxId() {
        return nxFollowUpActionId;
    }
    
    public void setNxId( int nxId ) {
        this.nxFollowUpActionId = nxId;
    }
    
    public ActionPojo getAction() {

        return this.action;
    }

    public void setAction( ActionPojo action ) {

        this.action = action;
    }

    public ActionPojo getFollowUpAction() {

        return this.followUpAction;
    }

    public void setFollowUpAction( ActionPojo followUpAction ) {

        this.followUpAction = followUpAction;
    }

    public Date getCreatedDate() {

        return this.createdDate;
    }

    public void setCreatedDate( Date createdDate ) {

        this.createdDate = createdDate;
    }

    public Date getModifiedDate() {

        return this.modifiedDate;
    }

    public void setModifiedDate( Date modifiedDate ) {

        this.modifiedDate = modifiedDate;
    }

    public int getModifiedNxUserId() {

        return this.modifiedNxUserId;
    }

    public void setModifiedNxUserId( int modifiedNxUserId ) {

        this.modifiedNxUserId = modifiedNxUserId;
    }

    /**
     * Required for JAXB 
     * @return
     */
    @XmlAttribute
    public int getNxActionId() {

        if ( this.action != null ) {
            return this.action.getNxActionId();
        }
        return nxActionId;
    }
    
    /**
     * Required for JAXB
     * @param actionId
     */
    public void setNxActionId( int actionId ) {
        this.nxActionId = actionId;
    }

    /**
     * Required for JAXB 
     * @return
     */
    @XmlAttribute
    public int getRefNxFollowUpActionId() {

        if ( this.followUpAction != null ) {
            return this.followUpAction.getNxActionId();
        }

        return refNxFollowUpActionId;
    }
    
    /**
     * Required for JAXB
     * @param followUpActionId
     */
    public void setRefNxFollowUpActionId( int followUpActionId ) {
        this.refNxFollowUpActionId = followUpActionId;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals( Object obj ) {

        if ( !( obj instanceof FollowUpActionPojo ) ) {
            return false;
        }

        if ( nxFollowUpActionId == 0 ) {
            return super.equals( obj );
        }

        return nxFollowUpActionId == ( (FollowUpActionPojo) obj ).nxFollowUpActionId;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {

        if ( nxFollowUpActionId == 0 ) {
            return super.hashCode();
        }

        return nxFollowUpActionId;
    }

    // this method is called by JAXB when a cycle is detected
    /*
    public ActionPojo onCycleDetected(Context context) {
        // when a cycle is detected, let's just write out an ID
        ActionPojo replacement = new ActionPojo();
        replacement.setNxActionId( action.getNxActionId() );
        return replacement;
    }
    */
}
