/**
 *  NEXUSe2e Business Messaging Open Source
 *  Copyright 2000-2009, Tamgroup and X-ioma GmbH
 *
 *  This is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as
 *  published by the Free Software Foundation version 2.1 of
 *  the License.
 *
 *  This software is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this software; if not, write to the Free
 *  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 *  02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.nexuse2e.pojo;

// Generated 15.12.2006 16:07:02 by Hibernate Tools 3.2.0.beta6a

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * GrantPojo generated by hbm2java
 */
@XmlType(name = "GrantType")
@XmlAccessorType(XmlAccessType.NONE )
public class GrantPojo implements NEXUSe2ePojo {

    // Fields    

    /**
     * 
     */
    private static final long serialVersionUID = -6954829251364806284L;
    private int               nxGrantId;
    private String            target;
    private Date              createdDate;
    private Date              modifiedDate;
    private int               modifiedNxUserId;

    // Constructors

    /** default constructor */
    public GrantPojo() {
        createdDate = new Date();
        modifiedDate = createdDate;
    }

    /** minimal constructor */
    public GrantPojo( String target, Date createdDate, Date modifiedDate, int modifiedNxUserId ) {

        this.target = target;
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.modifiedNxUserId = modifiedNxUserId;
    }

    // Property accessors
    public int getNxGrantId() {

        return this.nxGrantId;
    }

    public void setNxGrantId( int nxGrantId ) {

        this.nxGrantId = nxGrantId;
    }

    public int getNxId() {
        return nxGrantId;
    }
    
    public void setNxId( int nxId ) {
        this.nxGrantId = nxId;
    }
    
    @XmlAttribute
    public String getTarget() {

        return this.target;
    }

    public void setTarget( String target ) {

        this.target = target;
    }

    public Date getCreatedDate() {

        return this.createdDate;
    }

    public void setCreatedDate( Date createdDate ) {

        this.createdDate = createdDate;
    }

    public Date getModifiedDate() {

        return this.modifiedDate;
    }

    public void setModifiedDate( Date modifiedDate ) {

        this.modifiedDate = modifiedDate;
    }

    public int getModifiedNxUserId() {

        return this.modifiedNxUserId;
    }

    public void setModifiedNxUserId( int modifiedNxUserId ) {

        this.modifiedNxUserId = modifiedNxUserId;
    }
}
