/**
 *  NEXUSe2e Business Messaging Open Source
 *  Copyright 2000-2009, Tamgroup and X-ioma GmbH
 *
 *  This is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as
 *  published by the Free Software Foundation version 2.1 of
 *  the License.
 *
 *  This software is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this software; if not, write to the Free
 *  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 *  02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.nexuse2e.pojo;

// Generated 20.10.2006 15:50:01 by Hibernate Tools 3.2.0.beta6a

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * PipeletParamPojo generated by hbm2java
 */
@Entity
@Table(name = "nx_mapping")
@XmlType(name = "MappingType")
@XmlAccessorType(XmlAccessType.NONE)
public class MappingPojo implements NEXUSe2ePojo {

    /**
     * 
     */
    private static final long serialVersionUID = 0L;
    
    // Fields

    @Id
    @Column(name = "nx_mapping_id")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int    nxMappingId;

    @Column(name = "created_date", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date              createdDate;

    @Column(name = "modified_date", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date              modifiedDate;

    @Column(name = "modified_nx_user_id", nullable = false)
    private int               modifiedNxUserId;

    @Column(name = "category", length = 128, nullable = false)
    private String category;

    @Column(name = "left_type", nullable = false)
    private int    leftType;

    @Column(name = "left_value", length = 128, nullable = true)
    private String leftValue;

    @Column(name = "right_type", nullable = false)
    private int    rightType;

    @Column(name = "right_value", length = 128, nullable = true)
    private String rightValue;

    // Constructors

    /** default constructor */
    public MappingPojo() {

        createdDate = new Date();
        modifiedDate = createdDate;
    }

    /** minimal constructor */
    public MappingPojo( Date createdDate, Date modifiedDate, int modifiedNxUserId, String category, int leftType,
            String leftValue, int rightType, String rightValue ) {

        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.modifiedNxUserId = modifiedNxUserId;
        this.category = category;
        this.leftType = leftType;
        this.leftValue = leftValue;
        this.rightType = rightType;
        this.rightValue = rightValue;
    }

    @XmlAttribute
    public String getCategory() {

        return category;
    }

    public void setCategory( String category ) {

        this.category = category;
    }

    public Date getCreatedDate() {

        return createdDate;
    }

    public void setCreatedDate( Date createdDate ) {

        this.createdDate = createdDate;
    }

    @XmlAttribute
    public int getLeftType() {

        return leftType;
    }

    public void setLeftType( int leftType ) {

        this.leftType = leftType;
    }

    @XmlAttribute
    public String getLeftValue() {

        return leftValue;
    }

    public void setLeftValue( String leftValue ) {

        this.leftValue = leftValue;
    }

    public Date getModifiedDate() {

        return modifiedDate;
    }

    public void setModifiedDate( Date modifiedDate ) {

        this.modifiedDate = modifiedDate;
    }

    public int getModifiedNxUserId() {

        return modifiedNxUserId;
    }

    public void setModifiedNxUserId( int modifiedNxUserId ) {

        this.modifiedNxUserId = modifiedNxUserId;
    }

    @XmlAttribute
    public int getNxMappingId() {

        return nxMappingId;
    }

    public void setNxMappingId( int nxMappingId ) {

        this.nxMappingId = nxMappingId;
    }

    public int getNxId() {
        return nxMappingId;
    }
    
    public void setNxId( int nxId ) {
        this.nxMappingId = nxId;
    }
    
    @XmlAttribute
    public int getRightType() {

        return rightType;
    }

    public void setRightType( int rightType ) {

        this.rightType = rightType;
    }

    @XmlAttribute
    public String getRightValue() {

        return rightValue;
    }

    public void setRightValue( String rightValue ) {

        this.rightValue = rightValue;
    }

} // MappingPojo
