/**
 *  NEXUSe2e Business Messaging Open Source
 *  Copyright 2000-2009, Tamgroup and X-ioma GmbH
 *
 *  This is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as
 *  published by the Free Software Foundation version 2.1 of
 *  the License.
 *
 *  This software is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this software; if not, write to the Free
 *  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 *  02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.nexuse2e.pojo;

// Generated 20.10.2006 15:50:01 by Hibernate Tools 3.2.0.beta6a

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import org.nexuse2e.configuration.ParameterDescriptor;

/**
 * PipeletParamPojo generated by hbm2java
 */
@XmlType(name = "PipeletParamType")
@XmlAccessorType(XmlAccessType.NONE)
public class PipeletParamPojo implements NEXUSe2ePojo {

    /**
     * 
     */
    private static final long   serialVersionUID = 7032848325874669262L;

    // Fields    
    private int                 nxPipeletParamId;
    private PipeletPojo         pipelet;
    private Date                createdDate;
    private Date                modifiedDate;
    private int                 modifiedNxUserId;
    private String              paramName;
    private String              label;
    private String              value;
    private int                 sequenceNumber;

    // non-persistent fields
    private transient ParameterDescriptor parameterDescriptor;

    // Constructors

    /** default constructor */
    public PipeletParamPojo() {
        createdDate = new Date();
        modifiedDate = createdDate;
    }

    /** minimal constructor */
    public PipeletParamPojo( PipeletPojo pipelet, Date createdDate, Date modifiedDate, int modifiedNxUserId,
            String paramName, String value ) {

        this.pipelet = pipelet;
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.modifiedNxUserId = modifiedNxUserId;
        this.paramName = paramName;
        this.value = value;
    }

    /** full constructor */
    public PipeletParamPojo( PipeletPojo pipelet, Date createdDate, Date modifiedDate, int modifiedNxUserId,
            String paramName, String label, String value, int sequenceNumber ) {

        this.pipelet = pipelet;
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.modifiedNxUserId = modifiedNxUserId;
        this.paramName = paramName;
        this.label = label;
        this.value = value;
        this.sequenceNumber = sequenceNumber;
    }

    // Property accessors
    @XmlAttribute
    public int getNxPipeletParamId() {

        return this.nxPipeletParamId;
    }

    public void setNxPipeletParamId( int nxPipeletParamId ) {

        this.nxPipeletParamId = nxPipeletParamId;
    }

    public int getNxId() {
        return nxPipeletParamId;
    }
    
    public void setNxId( int nxId ) {
        this.nxPipeletParamId = nxId;
    }
    
    public PipeletPojo getPipelet() {

        return this.pipelet;
    }

    public void setPipelet( PipeletPojo pipelet ) {

        this.pipelet = pipelet;
    }

    public Date getCreatedDate() {

        return this.createdDate;
    }

    public void setCreatedDate( Date createdDate ) {

        this.createdDate = createdDate;
    }

    public Date getModifiedDate() {

        return this.modifiedDate;
    }

    public void setModifiedDate( Date modifiedDate ) {

        this.modifiedDate = modifiedDate;
    }

    public int getModifiedNxUserId() {

        return this.modifiedNxUserId;
    }

    public void setModifiedNxUserId( int modifiedNxUserId ) {

        this.modifiedNxUserId = modifiedNxUserId;
    }

    @XmlAttribute
    public String getParamName() {

        return this.paramName;
    }

    public void setParamName( String paramName ) {

        this.paramName = paramName;
    }

    @XmlAttribute
    public String getLabel() {

        return this.label;
    }

    public void setLabel( String label ) {

        this.label = label;
    }

    @XmlAttribute
    public String getValue() {

        return this.value;
    }

    public void setValue( String value ) {

        this.value = value;
    }

    @XmlAttribute
    public int getSequenceNumber() {

        return this.sequenceNumber;
    }

    public void setSequenceNumber( int sequenceNumber ) {

        this.sequenceNumber = sequenceNumber;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals( Object obj ) {

        if ( !( obj instanceof PipeletParamPojo ) ) {
            return false;
        }

        if ( nxPipeletParamId == 0 ) {
            return super.equals( obj );
        }

        return nxPipeletParamId == ( (PipeletParamPojo) obj ).nxPipeletParamId;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {

        if ( nxPipeletParamId == 0 ) {
            return super.hashCode();
        }

        return nxPipeletParamId;
    }

    /**
     * @return the parameterDescriptor
     */
    public ParameterDescriptor getParameterDescriptor() {

        return parameterDescriptor;
    }

    /**
     * @param parameterDescriptor the parameterDescriptor to set
     */
    public void setParameterDescriptor( ParameterDescriptor parameterDescriptor ) {

        this.parameterDescriptor = parameterDescriptor;
    }
}
