
package org.nexuse2e.service.ws.aggateway.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.2
 * 2013-04-24T15:21:51.848+02:00
 * Generated source version: 2.3.2
 * 
 */

@WebFault(name = "problem", targetNamespace = "urn:aggateway:names:ws:docexchange")
public class DocExchangeFault extends Exception {
    public static final long serialVersionUID = 20130424152151L;
    
    private java.lang.String problem;

    public DocExchangeFault() {
        super();
    }
    
    public DocExchangeFault(String message) {
        super(message);
    }
    
    public DocExchangeFault(String message, Throwable cause) {
        super(message, cause);
    }

    public DocExchangeFault(String message, java.lang.String problem) {
        super(message);
        this.problem = problem;
    }

    public DocExchangeFault(String message, java.lang.String problem, Throwable cause) {
        super(message, cause);
        this.problem = problem;
    }

    public java.lang.String getFaultInfo() {
        return this.problem;
    }
}
