/**
 * NEXUSe2e Business Messaging Open Source  
 * Copyright 2007, Tamgroup and X-ioma GmbH   
 *  
 * This is free software; you can redistribute it and/or modify it  
 * under the terms of the GNU Lesser General Public License as  
 * published by the Free Software Foundation version 2.1 of  
 * the License.  
 *  
 * This software is distributed in the hope that it will be useful,  
 * but WITHOUT ANY WARRANTY; without even the implied warranty of  
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU  
 * Lesser General Public License for more details.  
 *  
 * You should have received a copy of the GNU Lesser General Public  
 * License along with this software; if not, write to the Free  
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.nexuse2e.pojo;

import java.util.Date;

import org.apache.log4j.Logger;
import org.nexuse2e.configuration.Constants;

/**
 * CertificatePojo generated by hbm2java
 */
public class CertificatePojo implements java.io.Serializable {

//    Logger                    LOG              = Logger.getLogger( CertificatePojo.class );

    /**
     * 
     */
    private static final long serialVersionUID = 6193340972799640301L;

    // Fields    
    private int               nxCertificateId;
    private int               type;
    private String            password;
    private Date              createdDate;
    private Date              modifiedDate;
    private int               modifiedNxUserId;
    private PartnerPojo       partner;
    private String            name;
    private String            description;
    private byte[]            binaryData;

    // Constructors

    /** default constructor */
    public CertificatePojo() {

        createdDate = new Date();
        modifiedDate = createdDate;
    }

    /** minimal constructor */
    public CertificatePojo( int type, Date createdDate, Date modifiedDate, int modifiedNxUserId, PartnerPojo partner,
            String name, byte[] binaryData ) {

        this.type = type;
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.modifiedNxUserId = modifiedNxUserId;
        this.partner = partner;
        this.name = name;
        this.binaryData = binaryData;
    }

    /** full constructor */
    public CertificatePojo( int type, String password, Date createdDate, Date modifiedDate, int modifiedNxUserId,
            PartnerPojo partner, String name, String description, byte[] binaryData ) {

        this.type = type;
        this.password = password;
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.modifiedNxUserId = modifiedNxUserId;
        this.partner = partner;
        this.name = name;
        this.description = description;
        this.binaryData = binaryData;
    }

    // Property accessors
    public int getNxCertificateId() {

        return this.nxCertificateId;
    }

    public void setNxCertificateId( int nxCertificateId ) {

        this.nxCertificateId = nxCertificateId;
    }

    public int getType() {

        return this.type;
    }

    public void setType( int type ) {

        this.type = type;
    }

    public String getPassword() {

        return this.password;
    }

    public void setPassword( String password ) {

        this.password = password;
    }

    public Date getCreatedDate() {

        return this.createdDate;
    }

    public void setCreatedDate( Date createdDate ) {

        this.createdDate = createdDate;
    }

    public Date getModifiedDate() {

        return this.modifiedDate;
    }

    public void setModifiedDate( Date modifiedDate ) {

        this.modifiedDate = modifiedDate;
    }

    public int getModifiedNxUserId() {

        return this.modifiedNxUserId;
    }

    public void setModifiedNxUserId( int modifiedNxUserId ) {

        this.modifiedNxUserId = modifiedNxUserId;
    }

    public String getName() {

        return this.name;
    }

    public void setName( String name ) {

        this.name = name;
    }

    public String getDescription() {

        return this.description;
    }

    public void setDescription( String description ) {

        this.description = description;
    }

    public byte[] getBinaryData() {

        return this.binaryData;
    }

    public void setBinaryData( byte[] binaryData ) {

        this.binaryData = binaryData;
    }

    /**
     * @return the partner
     */
    public PartnerPojo getPartner() {

        return partner;
    }

    /**
     * @param partner the partner to set
     */
    public void setPartner( PartnerPojo partner ) {

        this.partner = partner;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals( Object obj ) {

        if ( !( obj instanceof CertificatePojo ) ) {
            return false;
        }
        if ( nxCertificateId == 0 ) {
            return super.equals( obj );
        }

        return nxCertificateId == ( (CertificatePojo) obj ).nxCertificateId;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {

        if ( nxCertificateId == 0 ) {
            return super.hashCode();
        }

        return nxCertificateId;
    }

    

    /**
     * Incuded Pojo Types: CA and PARTNER
     * 
     * @return
     */
    public boolean isX509() {

        if ( getType() == Constants.CERTIFICATE_TYPE_CA || getType() == Constants.CERTIFICATE_TYPE_PARTNER ) {
            return true;
        }
        return false;
    }

    /**
     * Included Pojo Types: CERT_PART, STAGING and LOCAL
     * 
     * @return
     */
    public boolean isPKCS12() {

        if (  getType() == Constants.CERTIFICATE_TYPE_STAGING
                || getType() == Constants.CERTIFICATE_TYPE_LOCAL ) {
            return true;
        }
        return false;
    }

    /**
     * Included Pojo Types: REQUEST
     * 
     * @return
     */
    public boolean isPKCS10() {

        if ( getType() == Constants.CERTIFICATE_TYPE_REQUEST ) {
            return true;
        }
        return false;
    }
}
