/**
 * NEXUSe2e Business Messaging Open Source  
 * Copyright 2007, Tamgroup and X-ioma GmbH   
 *  
 * This is free software; you can redistribute it and/or modify it  
 * under the terms of the GNU Lesser General Public License as  
 * published by the Free Software Foundation version 2.1 of  
 * the License.  
 *  
 * This software is distributed in the hope that it will be useful,  
 * but WITHOUT ANY WARRANTY; without even the implied warranty of  
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU  
 * Lesser General Public License for more details.  
 *  
 * You should have received a copy of the GNU Lesser General Public  
 * License along with this software; if not, write to the Free  
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.nexuse2e.pojo;

// Generated 20.10.2006 15:50:01 by Hibernate Tools 3.2.0.beta6a

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * FollowUpActionPojo generated by hbm2java
 */
/**
 * @author mbreilmann
 *
 */
@XmlType(name = "FollowUpActionType")
@XmlAccessorType(XmlAccessType.NONE)
public class FollowUpActionPojo implements java.io.Serializable {

    //    public class FollowUpActionPojo implements java.io.Serializable, com.sun.xml.bind.CycleRecoverable {

    /**
     * 
     */
    private static final long serialVersionUID = -8322100357883464751L;

    // Fields    
    private int               nxFollowUpActionId;
    private ActionPojo        action;
    private ActionPojo        followUpAction;
    private Date              createdDate;
    private Date              modifiedDate;
    private int               modifiedNxUserId;

    private int               nxActionId;
    private int               refNxFollowUpActionId;
    
    // Constructors

    /** default constructor */
    public FollowUpActionPojo() {

        createdDate = new Date();
        modifiedDate = createdDate;
    }

    /** full constructor */
    public FollowUpActionPojo( ActionPojo action, ActionPojo followUpAction, Date createdDate, Date modifiedDate,
            int modifiedNxUserId ) {

        this.action = action;
        this.followUpAction = followUpAction;
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.modifiedNxUserId = modifiedNxUserId;
    }

    // Property accessors
    @XmlAttribute
    public int getNxFollowUpActionId() {

        return this.nxFollowUpActionId;
    }

    public void setNxFollowUpActionId( int nxFollowUpActionId ) {

        this.nxFollowUpActionId = nxFollowUpActionId;
    }

    public ActionPojo getAction() {

        return this.action;
    }

    public void setAction( ActionPojo action ) {

        this.action = action;
    }

    public ActionPojo getFollowUpAction() {

        return this.followUpAction;
    }

    public void setFollowUpAction( ActionPojo followUpAction ) {

        this.followUpAction = followUpAction;
    }

    public Date getCreatedDate() {

        return this.createdDate;
    }

    public void setCreatedDate( Date createdDate ) {

        this.createdDate = createdDate;
    }

    public Date getModifiedDate() {

        return this.modifiedDate;
    }

    public void setModifiedDate( Date modifiedDate ) {

        this.modifiedDate = modifiedDate;
    }

    public int getModifiedNxUserId() {

        return this.modifiedNxUserId;
    }

    public void setModifiedNxUserId( int modifiedNxUserId ) {

        this.modifiedNxUserId = modifiedNxUserId;
    }

    /**
     * Required for JAXB 
     * @return
     */
    @XmlAttribute
    public int getNxActionId() {

        if ( this.action != null ) {
            return this.action.getNxActionId();
        }
        return nxActionId;
    }
    
    /**
     * Required for JAXB
     * @param actionId
     */
    public void setNxActionId( int actionId ) {
        this.nxActionId = actionId;
    }

    /**
     * Required for JAXB 
     * @return
     */
    @XmlAttribute
    public int getRefNxFollowUpActionId() {

        if ( this.followUpAction != null ) {
            return this.followUpAction.getNxActionId();
        }

        return refNxFollowUpActionId;
    }
    
    /**
     * Required for JAXB
     * @param followUpActionId
     */
    public void setRefNxFollowUpActionId( int followUpActionId ) {
        this.refNxFollowUpActionId = followUpActionId;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals( Object obj ) {

        if ( !( obj instanceof FollowUpActionPojo ) ) {
            return false;
        }

        if ( nxFollowUpActionId == 0 ) {
            return super.equals( obj );
        }

        return nxFollowUpActionId == ( (FollowUpActionPojo) obj ).nxFollowUpActionId;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {

        if ( nxFollowUpActionId == 0 ) {
            return super.hashCode();
        }

        return nxFollowUpActionId;
    }

    // this method is called by JAXB when a cycle is detected
    /*
    public ActionPojo onCycleDetected(Context context) {
        // when a cycle is detected, let's just write out an ID
        ActionPojo replacement = new ActionPojo();
        replacement.setNxActionId( action.getNxActionId() );
        return replacement;
    }
    */
}
