/**
 * NEXUSe2e Business Messaging Open Source  
 * Copyright 2007, Tamgroup and X-ioma GmbH   
 *  
 * This is free software; you can redistribute it and/or modify it  
 * under the terms of the GNU Lesser General Public License as  
 * published by the Free Software Foundation version 2.1 of  
 * the License.  
 *  
 * This software is distributed in the hope that it will be useful,  
 * but WITHOUT ANY WARRANTY; without even the implied warranty of  
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU  
 * Lesser General Public License for more details.  
 *  
 * You should have received a copy of the GNU Lesser General Public  
 * License along with this software; if not, write to the Free  
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.nexuse2e.pojo;

// Generated 22.12.2006 15:46:31 by Hibernate Tools 3.2.0.beta6a

import java.util.Date;

/**
 * LogPojo generated by hbm2java
 */
public class LogPojo implements java.io.Serializable {

    // Fields    

    /**
     * 
     */
    private static final long serialVersionUID = 7490281001286462405L;
    private int               nxLogId;
    private String            logId;
    private String            className;
    private String            methodName;
    private int               eventId;
    private int               severity;
    private String            conversationId;
    private String            messageId;
    private String            description;
    private Date              createdDate;

    // Constructors

    /** default constructor */
    public LogPojo() {
        createdDate = new Date();
    }

    /** full constructor */
    public LogPojo( String logId, String className, String methodName, int eventId, int severity,
            String conversationId, String messageId, String description, Date createdDate ) {

        this.logId = logId;
        this.className = className;
        this.methodName = methodName;
        this.eventId = eventId;
        this.severity = severity;
        this.conversationId = conversationId;
        this.messageId = messageId;
        this.description = description;
        this.createdDate = createdDate;
    }

    // Property accessors
    public int getNxLogId() {

        return this.nxLogId;
    }

    public void setNxLogId( int nxLogId ) {

        this.nxLogId = nxLogId;
    }

    public String getLogId() {

        return this.logId;
    }

    public void setLogId( String logId ) {

        this.logId = logId;
    }

    public String getClassName() {

        return this.className;
    }

    public void setClassName( String className ) {

        this.className = className;
    }

    public String getMethodName() {

        return this.methodName;
    }

    public void setMethodName( String methodName ) {

        this.methodName = methodName;
    }

    public int getEventId() {

        return this.eventId;
    }

    public void setEventId( int eventId ) {

        this.eventId = eventId;
    }

    public int getSeverity() {

        return this.severity;
    }

    public void setSeverity( int severity ) {

        this.severity = severity;
    }

    public String getConversationId() {

        return this.conversationId;
    }

    public void setConversationId( String conversationId ) {

        this.conversationId = conversationId;
    }

    public String getMessageId() {

        return this.messageId;
    }

    public void setMessageId( String messageId ) {

        this.messageId = messageId;
    }

    public String getDescription() {

        return this.description;
    }

    public void setDescription( String description ) {

        this.description = description;
    }

    public Date getCreatedDate() {

        return this.createdDate;
    }

    public void setCreatedDate( Date createdDate ) {

        this.createdDate = createdDate;
    }

}
