/**
 * NEXUSe2e Business Messaging Open Source  
 * Copyright 2007, Tamgroup and X-ioma GmbH   
 *  
 * This is free software; you can redistribute it and/or modify it  
 * under the terms of the GNU Lesser General Public License as  
 * published by the Free Software Foundation version 2.1 of  
 * the License.  
 *  
 * This software is distributed in the hope that it will be useful,  
 * but WITHOUT ANY WARRANTY; without even the implied warranty of  
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU  
 * Lesser General Public License for more details.  
 *  
 * You should have received a copy of the GNU Lesser General Public  
 * License along with this software; if not, write to the Free  
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.nexuse2e.pojo;

// Generated 20.10.2006 15:50:01 by Hibernate Tools 3.2.0.beta6a

import java.util.Date;

/**
 * MessageLabelPojo generated by hbm2java
 */
public class MessageLabelPojo implements NEXUSe2ePojo {

    /**
     * 
     */
    private static final long serialVersionUID = -3388448752721707618L;

    // Fields    
    private int               nxMessageLabelId;
    private MessagePojo       message;
    private Date              createdDate;
    private Date              modifiedDate;
    private int               modifiedNxUserId;
    private String            label;
    private String            value;

    // Constructors

    /** default constructor */
    public MessageLabelPojo() {
        createdDate = new Date();
        modifiedDate = createdDate;
    }

    /** minimal constructor */
    public MessageLabelPojo( MessagePojo message, Date createdDate, Date modifiedDate, int modifiedNxUserId,
            String value ) {

        this.message = message;
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.modifiedNxUserId = modifiedNxUserId;
        this.value = value;
    }

    /** full constructor */
    public MessageLabelPojo( MessagePojo message, Date createdDate, Date modifiedDate, int modifiedNxUserId,
            String label, String value ) {

        this.message = message;
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.modifiedNxUserId = modifiedNxUserId;
        this.label = label;
        this.value = value;
    }

    // Property accessors
    public int getNxMessageLabelId() {

        return this.nxMessageLabelId;
    }

    public void setNxMessageLabelId( int nxMessageLabelId ) {

        this.nxMessageLabelId = nxMessageLabelId;
    }

    public int getNxId() {
        return nxMessageLabelId;
    }
    
    public void setNxId( int nxId ) {
        this.nxMessageLabelId = nxId;
    }
    
    public MessagePojo getMessage() {

        return this.message;
    }

    public void setMessage( MessagePojo message ) {

        this.message = message;
    }

    public Date getCreatedDate() {

        return this.createdDate;
    }

    public void setCreatedDate( Date createdDate ) {

        this.createdDate = createdDate;
    }

    public Date getModifiedDate() {

        return this.modifiedDate;
    }

    public void setModifiedDate( Date modifiedDate ) {

        this.modifiedDate = modifiedDate;
    }

    public int getModifiedNxUserId() {

        return this.modifiedNxUserId;
    }

    public void setModifiedNxUserId( int modifiedNxUserId ) {

        this.modifiedNxUserId = modifiedNxUserId;
    }

    public String getLabel() {

        return this.label;
    }

    public void setLabel( String label ) {

        this.label = label;
    }

    public String getValue() {

        return this.value;
    }

    public void setValue( String value ) {

        this.value = value;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#clone()
     */
    @Override
    public Object clone() throws CloneNotSupportedException {
        MessageLabelPojo clonedMessageLabelPojo = new MessageLabelPojo();
        
        clonedMessageLabelPojo.setLabel( label );
        clonedMessageLabelPojo.setValue( value );
        clonedMessageLabelPojo.setCreatedDate( createdDate );
        clonedMessageLabelPojo.setModifiedDate( modifiedDate );
        clonedMessageLabelPojo.setModifiedNxUserId( modifiedNxUserId );
        clonedMessageLabelPojo.setMessage( message );
        
        return clonedMessageLabelPojo;
    }
    
    /* (non-Javadoc)
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals( Object obj ) {

        if ( obj instanceof MessageLabelPojo ) {
            if ( nxMessageLabelId == 0 ) {
                return super.equals( obj );
            }
            return ( nxMessageLabelId == ( (MessageLabelPojo) obj ).getNxMessageLabelId() );
        }

        return false;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {

        if ( nxMessageLabelId == 0 ) {
            return super.hashCode();
        }

        return nxMessageLabelId;
    }

}
