/**
 * NEXUSe2e Business Messaging Open Source  
 * Copyright 2007, Tamgroup and X-ioma GmbH   
 *  
 * This is free software; you can redistribute it and/or modify it  
 * under the terms of the GNU Lesser General Public License as  
 * published by the Free Software Foundation version 2.1 of  
 * the License.  
 *  
 * This software is distributed in the hope that it will be useful,  
 * but WITHOUT ANY WARRANTY; without even the implied warranty of  
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU  
 * Lesser General Public License for more details.  
 *  
 * You should have received a copy of the GNU Lesser General Public  
 * License along with this software; if not, write to the Free  
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.nexuse2e.pojo;

// Generated 15.12.2006 16:07:02 by Hibernate Tools 3.2.0.beta6a

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * RolePojo generated by hbm2java
 */
public class RolePojo implements java.io.Serializable {

    // Fields    

    private static final long      serialVersionUID = 4542844458155873891L;

    private int                    nxRoleId;
    private String                 name;
    private String                 description;
    private Date                   createdDate;
    private Date                   modifiedDate;
    private int                    modifiedNxUserId;
    private Map<String, GrantPojo> grants           = new HashMap<String, GrantPojo>( 0 );

    // Constructors

    /** default constructor */
    public RolePojo() {
        createdDate = new Date();
        modifiedDate = createdDate;
    }

    /** minimal constructor */
    public RolePojo( String name, Date createdDate, Date modifiedDate, int modifiedNxUserId ) {

        this.name = name;
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.modifiedNxUserId = modifiedNxUserId;
    }

    /** full constructor */
    public RolePojo( String name, String description, Date createdDate, Date modifiedDate, int modifiedNxUserId,
            Map<String, GrantPojo> grants ) {

        this.name = name;
        this.description = description;
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.modifiedNxUserId = modifiedNxUserId;
        this.grants = grants;
    }

    // Property accessors
    public int getNxRoleId() {

        return this.nxRoleId;
    }

    public void setNxRoleId( int nxRoleId ) {

        this.nxRoleId = nxRoleId;
    }

    public String getName() {

        return this.name;
    }

    public void setName( String name ) {

        this.name = name;
    }

    public String getDescription() {

        return this.description;
    }

    public void setDescription( String description ) {

        this.description = description;
    }

    public Date getCreatedDate() {

        return this.createdDate;
    }

    public void setCreatedDate( Date createdDate ) {

        this.createdDate = createdDate;
    }

    public Date getModifiedDate() {

        return this.modifiedDate;
    }

    public void setModifiedDate( Date modifiedDate ) {

        this.modifiedDate = modifiedDate;
    }

    public int getModifiedNxUserId() {

        return this.modifiedNxUserId;
    }

    public void setModifiedNxUserId( int modifiedNxUserId ) {

        this.modifiedNxUserId = modifiedNxUserId;
    }

    public Map<String, GrantPojo> getGrants() {

        return this.grants;
    }

    public void setGrants( Map<String, GrantPojo> grants ) {

        this.grants = grants;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals( Object obj ) {

        if ( !( obj instanceof RolePojo ) ) {
            return false;
        }

        if ( nxRoleId == 0 ) {
            return super.equals( obj );
        }

        return nxRoleId == ( (RolePojo) obj ).nxRoleId;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {

        if ( nxRoleId == 0 ) {
            return super.hashCode();
        }

        return nxRoleId;
    }
}
