/**
 * NEXUSe2e Business Messaging Open Source  
 * Copyright 2007, Tamgroup and X-ioma GmbH   
 *  
 * This is free software; you can redistribute it and/or modify it  
 * under the terms of the GNU Lesser General Public License as  
 * published by the Free Software Foundation version 2.1 of  
 * the License.  
 *  
 * This software is distributed in the hope that it will be useful,  
 * but WITHOUT ANY WARRANTY; without even the implied warranty of  
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU  
 * Lesser General Public License for more details.  
 *  
 * You should have received a copy of the GNU Lesser General Public  
 * License along with this software; if not, write to the Free  
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.nexuse2e.pojo;

// Generated 04.01.2007 15:39:42 by Hibernate Tools 3.2.0.beta6a

import java.util.Date;
import java.util.List;
import java.util.Vector;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * ServicePojo generated by hbm2java
 */
@XmlType(name = "ServiceType")
@XmlAccessorType(XmlAccessType.NONE)
public class ServicePojo implements java.io.Serializable {

    /**
     * 
     */
    private static final long      serialVersionUID = 1602063679628056983L;

    // Fields    
    private int                    nxServiceId;
    private ComponentPojo          component;
    private Date                   createdDate;
    private Date                   modifiedDate;
    private int                    modifiedNxUserId;
    private int                    position;
    private boolean                autostart;
    private String                 name;
    private String                 description;
    private List<ServiceParamPojo> serviceParams    = new Vector<ServiceParamPojo>( 0 );

    // Constructors

    /** default constructor */
    public ServicePojo() {

        createdDate = new Date();
        modifiedDate = createdDate;
    }

    /** minimal constructor */
    public ServicePojo( ComponentPojo component, Date createdDate, Date modifiedDate, int modifiedNxUserId,
            int position, String name ) {

        this.component = component;
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.modifiedNxUserId = modifiedNxUserId;
        this.position = position;
        this.name = name;
    }

    /** full constructor */
    public ServicePojo( ComponentPojo component, Date createdDate, Date modifiedDate, int modifiedNxUserId,
            int position, String name, String description, List<ServiceParamPojo> serviceParams ) {

        this.component = component;
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.modifiedNxUserId = modifiedNxUserId;
        this.position = position;
        this.name = name;
        this.description = description;
        this.serviceParams = serviceParams;
    }

    // Property accessors
    public int getNxServiceId() {

        return this.nxServiceId;
    }

    public void setNxServiceId( int nxServiceId ) {

        this.nxServiceId = nxServiceId;
    }

    public ComponentPojo getComponent() {

        return this.component;
    }

    public void setComponent( ComponentPojo component ) {

        this.component = component;
    }

    public Date getCreatedDate() {

        return this.createdDate;
    }

    public void setCreatedDate( Date createdDate ) {

        this.createdDate = createdDate;
    }

    public Date getModifiedDate() {

        return this.modifiedDate;
    }

    public void setModifiedDate( Date modifiedDate ) {

        this.modifiedDate = modifiedDate;
    }

    public int getModifiedNxUserId() {

        return this.modifiedNxUserId;
    }

    public void setModifiedNxUserId( int modifiedNxUserId ) {

        this.modifiedNxUserId = modifiedNxUserId;
    }

    public int getPosition() {

        return this.position;
    }

    public void setPosition( int position ) {

        this.position = position;
    }

    public String getName() {

        return this.name;
    }

    public void setName( String name ) {

        this.name = name;
    }

    public String getDescription() {

        return this.description;
    }

    public void setDescription( String description ) {

        this.description = description;
    }

    public List<ServiceParamPojo> getServiceParams() {

        return this.serviceParams;
    }

    public void setServiceParams( List<ServiceParamPojo> serviceParams ) {

        this.serviceParams = serviceParams;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals( Object obj ) {

        if ( !( obj instanceof ServicePojo ) ) {
            return false;
        }

        if ( nxServiceId == 0 ) {
            return super.equals( obj );
        }

        return nxServiceId == ( (ServicePojo) obj ).nxServiceId;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {

        if ( nxServiceId == 0 ) {
            return super.hashCode();
        }

        return nxServiceId;
    }

    
    public boolean isAutostart() {
    
        return autostart;
    }

    
    public void setAutostart( boolean autostart ) {
    
        this.autostart = autostart;
    }

}
