
package org.nexuse2e.service.ws.aggateway.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import org.nexuse2e.service.ws.aggateway.wsdl.DocExchangePortType;

/**
 * This class was generated by Apache CXF 2.0.8
 * Tue Sep 23 14:02:48 CEST 2008
 * Generated source version: 2.0.8
 * 
 */

@WebServiceClient(name = "AgGatewayDocumentExchange", 
                  wsdlLocation = "file:/Users/jr/Projekte/nexus/customers/AgGateway/apache-cxf-2.0.8/samples/wsdl_first_aggateway/wsdl/AgGatewaywParameters.wsdl",
                  targetNamespace = "urn:aggateway:names:ws:docexchange") 
public class AgGatewayDocumentExchange extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("urn:aggateway:names:ws:docexchange", "AgGatewayDocumentExchange");
    public final static QName AgGatewayDocumentExchangePort = new QName("urn:aggateway:names:ws:docexchange", "AgGatewayDocumentExchangePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/jr/Projekte/nexus/customers/AgGateway/apache-cxf-2.0.8/samples/wsdl_first_aggateway/wsdl/AgGatewaywParameters.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/Users/jr/Projekte/nexus/customers/AgGateway/apache-cxf-2.0.8/samples/wsdl_first_aggateway/wsdl/AgGatewaywParameters.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public AgGatewayDocumentExchange(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AgGatewayDocumentExchange(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgGatewayDocumentExchange() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns AgGatewayDocumentExchangePort
     */
    @WebEndpoint(name = "AgGatewayDocumentExchangePort")
    public DocExchangePortType getAgGatewayDocumentExchangePort() {
        return super.getPort(AgGatewayDocumentExchangePort, DocExchangePortType.class);
    }

}
