package org.nexuse2e.service.ws.aggateway.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.1.2
 * Mon Sep 29 11:38:40 CEST 2008
 * Generated source version: 2.1.2
 * 
 */
 
@WebService(targetNamespace = "urn:aggateway:names:ws:docexchange", name = "DocExchangePortType")
// @XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DocExchangePortType {

    @WebResult(name = "result", targetNamespace = "", partName = "result")
    @WebMethod(action = "execute")
    public OutboundData execute(
        @WebParam(partName = "parameters", name = "inboundData", targetNamespace = "urn:aggateway:names:ws:docexchange")
        InboundData parameters
    ) throws DocExchangeFault;
}
