
package org.nexuse2e.service.ws.aggateway.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.0.8
 * Tue Sep 23 14:02:48 CEST 2008
 * Generated source version: 2.0.8
 * 
 */

@WebFault(name = "problem", targetNamespace = "http://www.w3.org/2001/XMLSchema")

public class DocExchangeFault extends Exception {
    public static final long serialVersionUID = 20080923140248L;
    
    private java.lang.String problem;

    public DocExchangeFault() {
        super();
    }
    
    public DocExchangeFault(String message) {
        super(message);
    }
    
    public DocExchangeFault(String message, Throwable cause) {
        super(message, cause);
    }

    public DocExchangeFault(String message, java.lang.String problem) {
        super(message);
        this.problem = problem;
    }

    public DocExchangeFault(String message, java.lang.String problem, Throwable cause) {
        super(message, cause);
        this.problem = problem;
    }

    public java.lang.String getFaultInfo() {
        return this.problem;
    }
}
