
package org.nexuse2e.service.ws.aggateway.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;

/**
 * This class was generated by Apache CXF 2.0.8
 * Tue Sep 23 14:02:48 CEST 2008
 * Generated source version: 2.0.8
 * 
 */

@WebService(targetNamespace = "urn:aggateway:names:ws:docexchange", name = "DocExchangePortType")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)

public interface DocExchangePortType {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "result", targetNamespace = "", partName = "result")
    @WebMethod(action = "execute")
    public org.nexuse2e.service.ws.aggateway.wsdl.OutboundData execute(
        @WebParam(partName = "parameters", name = "inboundData", targetNamespace = "urn:aggateway:names:ws:docexchange")
        InboundData parameters
    ) throws DocExchangeFault;
}
