<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://ws.nexuse2e.org/SimpleXMLDocService/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="SimpleXMLDocService"
	targetNamespace="http://ws.nexuse2e.org/SimpleXMLDocService/">
	<wsdl:types>
		<xsd:schema
			targetNamespace="http://ws.nexuse2e.org/SimpleXMLDocService/">
			<xsd:element name="handleXMLDocResponse" type="xsd:anyType" />
			<xsd:element name="handleXMLDocRequest" type="xsd:anyType" />
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="handleXMLDocResponse">
		<wsdl:part element="tns:handleXMLDocResponse"
			name="handleXMLDocResponse" />
	</wsdl:message>
	<wsdl:message name="handleXMLDocRequest">
		<wsdl:part element="tns:handleXMLDocRequest"
			name="handleXMLDocRequest" />
	</wsdl:message>
	<wsdl:portType name="SimpleXMLDocServicePortType">
		<wsdl:operation name="handleXMLDoc">
			<wsdl:input message="tns:handleXMLDocRequest" />
			<wsdl:output message="tns:handleXMLDocResponse" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="SimpleXMLDocServiceSOAP" type="tns:SimpleXMLDocServicePortType">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="handleXMLDoc">
			<soap:operation
				soapAction="handleXMLDoc" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="SimpleXMLDocService">
		<wsdl:port binding="tns:SimpleXMLDocServiceSOAP" name="SimpleXMLDocServiceSOAP">
			<soap:address location="http://localhost:8080/NEXUSe2e/handler/SimpleXMLDocService" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
